relativeURLs = true
title = "Iris Margetis"
theme = "academimal"
sectionPagesMenu = "main"
defaultContentLanguage = "en"
ignorefiles = [ "hugo_travis_ci", ".travis.yml" ]

[params]
    shortbio = "PhD Candidate, Environmental, Urban & Applied Microeconomics, Michigan State University"
    logo = "images/Iris_Margetis_Professional_Headshot.jpg" 
    
